//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Meals
    {
        public long Id { get; set; }
        public int Q { get; set; }
        public bool IsCombo { get; set; }
        public bool IsSpicy { get; set; }
        public long Meal_Id { get; set; }
        public long Order_Id { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Order Order { get; set; }
    }
}
